" General Settings
set nocompatible              " Use Vim settings, not Vi
set encoding=utf-8           " Set UTF-8 encoding
set smartindent              " Enable smart indenting
set autoindent               " Enable auto indenting
set tabstop=4                " Set tab width to 4 spaces
set softtabstop=4             " Set tab width to 4 spaces when using the tab key
set shiftwidth=4             " Set indentation width to 4 spaces
set expandtab                " Use spaces instead of tabs
set number                   " Show line numbers
set relativenumber           " Use relative line numbers
set showcmd                  " Display incomplete commands

" Search and Highlighting
set hlsearch                 " Highlight search results
set incsearch                " Incremental search
set ignorecase               " Ignore case when searching
set smartcase                " Override 'ignorecase' if search pattern contains uppercase characters
set showmatch                " Show matching parentheses, braces, and so on

" Appearance
syntax enable                " Enable syntax highlighting
colorscheme desert           " Set color scheme (change as desired)
set background=dark         " Set dark background

" Key Mapping
nnoremap <C-p> :Files<CR>    " Map Ctrl+p to open file explorer

" Plugin Manager (assuming you're using Vim-Plug)

" Autocomplete/Autosuggestion Plugin
" call plug#begin('~/.vim/plugged')
" Coc.nvim 
" Plug 'neoclide/coc.nvim', {branch': 'release'}
" call plug#end()

" Save and Restore Session
set undofile                 " Enable undo history between sessions
set undodir=~/.vim/undo      " Set undo directory
set autowrite                " Automatically save files before operations

" Miscellaneous
set hidden                   " Enable background buffers
set mouse=a                  " Enable mouse support

" Abbreviations and Commands
iabbrev dd date              " Create an abbreviation

" Highlight the current line
set cursorline

" Highlight the current column
set cursorcolumn

" Set the cursor line highlighting for Monokai Pro to light gray
highlight CursorLine guibg=lightgray ctermbg=8

" Set the cursor column highlighting for Monokai Pro to light gray
highlight CursorColumn guibg=lightgray ctermbg=8

" Set the text highlighting for Monokai Pro to black
highlight Visual guifg=black guibg=NONE ctermfg=black ctermbg=NONE

" Autocomplete Suggestion 
set completeopt+=longest
set completeopt-=menu

" Custom Functions
" To be Added 

" Animated Startup 
" To be Added 
